### ISSUE TITLE
use of % operator in this library

### ISSUE THREAD

**Issue by Phirefly9** [gberrante/map_3d#2]
your `enu2aer` function, and I assume anywhere else you use the % operator will have results different from pymap3d.  In rust % is the remainder operator, and has different behavior than python's % operator.  you should be using `e.atan2(n).rem_euclid(std::f64::consts::PI *2.0)` to get the same results

**Comment by gberrante** [comment]
fixed dc2b155495bd70976f648d53727ae30a5e2dbbd0
