### ISSUE TITLE
License shows as non-standard in cargo registry

### ISSUE THREAD

**Issue by gassajor000** [gberrante/map_3d#4]
The Cargo.toml file is currently configured to set the license as "Non Standard", which is how it appears on crates.io. It looks like you are actually using the Apache 2.0 license which is a standard license and supported by crates.io. This is a small issue but for those of us with strict licensing requirements it requires getting special approval to use this package. 
![image](https://user-images.githubusercontent.com/43421414/172248037-e4bf54e4-71c7-4ace-b2d4-9f4da0207101.png)

To change this I believe you just have to put `license = "Apache-2.0"` in your Crates.toml file so the builder will update it in the crate metadata.

**Comment by gberrante** [comment]
license reference updated 614064273e708431c945f469e57daa3004a63935
