### ISSUE TITLE
Release 0.1.5 breaks semver

### ISSUE THREAD

**Issue by clintfred** [gberrante/map_3d#6]
Thank so much for your work on this crate! It's been very useful.

I picked up the `0.1.5` release today and it doesn't seem to be backwards compatible with `0.1.4`. 

The compiler error looks like:
```
219 |         let (lat_rad, lon_rad, alt_m) = map_3d::ecef2geodetic(x_m, y_m, z_m);
    |                                         ^^^^^^^^^^^^^^^^^^^^^--------------- an argument of type `Ellipsoid` is missing
```
If this API change was intentional, I think `0.1.5` should be re-released as `0.2.0`.

**Comment by gberrante** [comment]
hello, i was not aware of the semantic versioning rules. This library was born as an exercise for learning rust. 
Eventually for the next changes, i will keep the semver in mind. As of now i will keep the current version number.
