### ISSUE TITLE
no rotation matrix which transform enu/ned into xyz

### ISSUE THREAD

**Issue by Lishen1** [gberrante/map_3d#8]
it would be useful to have such rotation matrix (r3*r1) [https://gssc.esa.int/navipedia/index.php/Transformations_between_ECEF_and_ENU_coordinates](url) to transform not only point coordinates but orientation too

**Comment by gberrante** [comment]
you can transform enu/ned to geodetic and use lat and long to calculate the rotation matrix. 
Anyway orientation calculation should be done via quaternion and not rotation matrices with euler angle represantion
